# Generated by Django 2.0.2 on 2018-02-25 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2018, 3, 4, 12, 35, 45, 484476, tzinfo=utc))),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
